name: Generate Docs

on:
  push:
    branches: [ "main" ]
    
jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: langroodi/doxygenize@v1.7.0
      with:
        htmloutput: './docs/html'
        ghpagesbranch: 'master'
        ghpagesdir: './docs/'
        darkmode: true
    
